package DCMSApp;


/**
* DCMSApp/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Monday, June 18, 2018 12:17:10 AM EDT
*/

public interface DCMSOperations 
{
  String sayHello ();
  String createTRecord (String remoteInput, String managerID);
  String createSRecord (String remoteInput, String managerID);
  String editRecord (String remoteInput, String managerID);
  String getRecordCounts (String managerID);
  String transferRecord (String remoteInput, String managerID);
  String acceptTransferredRecord (String remoteInput, String managerID);
  void shutdown ();
} // interface DCMSOperations
