package DCMSApp;

/**
* DCMSApp/DCMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Tuesday, June 19, 2018 12:43:09 PM EDT
*/

public final class DCMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DCMSApp.DCMS value = null;

  public DCMSHolder ()
  {
  }

  public DCMSHolder (DCMSApp.DCMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCMSApp.DCMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCMSApp.DCMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCMSApp.DCMSHelper.type ();
  }

}
