package DCMSApp;


/**
* DCMSApp/DCMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Monday, June 18, 2018 12:17:10 AM EDT
*/

public abstract class DCMSPOA extends org.omg.PortableServer.Servant
 implements DCMSApp.DCMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("createTRecord", new java.lang.Integer (1));
    _methods.put ("createSRecord", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("getRecordCounts", new java.lang.Integer (4));
    _methods.put ("transferRecord", new java.lang.Integer (5));
    _methods.put ("acceptTransferredRecord", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DCMSApp/DCMS/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DCMSApp/DCMS/createTRecord
       {
         String remoteInput = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createTRecord (remoteInput, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DCMSApp/DCMS/createSRecord
       {
         String remoteInput = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createSRecord (remoteInput, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DCMSApp/DCMS/editRecord
       {
         String remoteInput = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.editRecord (remoteInput, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DCMSApp/DCMS/getRecordCounts
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DCMSApp/DCMS/transferRecord
       {
         String remoteInput = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.transferRecord (remoteInput, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DCMSApp/DCMS/acceptTransferredRecord
       {
         String remoteInput = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.acceptTransferredRecord (remoteInput, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DCMSApp/DCMS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DCMSApp/DCMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DCMS _this() 
  {
    return DCMSHelper.narrow(
    super._this_object());
  }

  public DCMS _this(org.omg.CORBA.ORB orb) 
  {
    return DCMSHelper.narrow(
    super._this_object(orb));
  }


} // class DCMSPOA
