package DCMSApp;


/**
* DCMSApp/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Friday, June 15, 2018 6:17:44 PM EDT
*/

public interface DCMSOperations 
{
  String sayHello ();
  String createTRecord (String remoteInput, String managerID);
  String createSRecord (String remoteInput, String managerID);
  String editRecord (String remoteInput, String managerID);
  String getRecordCounts (String managerID);
  String transferRecord (String remoteInput, String managerID);
  void shutdown ();
} // interface DCMSOperations
