package DCMSApp;


/**
* DCMSApp/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Monday, June 18, 2018 12:17:10 AM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
